apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-app
  name: test-app
  namespace: zakir-team-ns-1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: test-app
        env:
        - name: COLOR
          value: "Green"
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: v1
      volumes:
      - name: v1
        emptyDir: {}
